[workspace]

[package]
name = "kubelike"
version = "0.1.0"
edition = "2021"

[dependencies]
standout = "=9.0.0"
standout-dispatch = "=9.0.0"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
anyhow = "1"
